parameters:
#    hack_translate_translate.example.class: HackTranslate\TranslateBundle\Example

services:
#    hack_translate_translate.example:
#        class: %hack_translate_translate.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
